services:
  api-service:
    container_name: api_container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8085:8080"
    networks:
      - backend_api_network
    depends_on:
      - mysql
  mysql:
    container_name: movie_booking_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: daokhanh3920
      MYSQL_DATABASE: movie_booking_db
      MYSQL_USER: root
      MYSQL_PASSWORD: daokhanh3920
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - backend_api_network

networks:
  backend_api_network:
    driver: bridge

volumes:
  db_data:
