spring:
    application:
        name: cinema-booking
    profiles:
        active: dev
    datasource:
        url: jdbc:mysql://localhost:3306/movie_booking_db
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: daokhanh3920

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
        
