server:
    port: 8081
spring:
    config:
        activate:
            on-profile: test
openapi:
    service:
        title: API Document test
        version: v1.0.2
        description: My API Descripsion
        serverUrl:  http://localhost:${server.port}
        serverName: Server Test1